= BC Drill Manager

A Ruby library with a companion script to ease an organization's
management of business continuity-related (BC) drill reports.

== Motivation

By utilizing models defined in
https://github.com/riboseinc/bc-drill-model/[BC Drill Model],
this project attempts to bring formalization to BC drill report documents.

This enables integration with other automation tools such as continuous
integration platforms.

== Installation

=== as a library (TBI)

. Put this in your `Gemfile`:
+
[source,ruby]
----
gem "bc-drill-manager"
----

. Run `bundle` in your console.

Or install it yourself as:

[source,bash]
....
gem install bc-drill-manager
....

Now you can use this library within your Ruby app! (TODO: elaborate)

=== as a script (TBI)

. Clone this repo:
+
[source,bash]
----
git clone https://github.com/riboseinc/bc-drill-manager
cd bc-drill-manager
----

. Run `bundle` in your console.
. The script is now available in your console! (TODO: elaborate)
+
[source,bash]
----
driller --version
----

== Development

After checking out the repo, run `bin/setup` to install dependencies. Then, run
`rake spec` to run the tests. You can also run `bin/console` for an interactive
prompt that will allow you to experiment.

To install this gem onto your local machine, run `bundle exec rake install`. To
release a new version, update the version number in `version.rb`, and then run
`bundle exec rake release`, which will create a git tag for the version, push
git commits and tags, and push the `.gem` file to
https://rubygems.org[rubygems.org].

== Contributing

Bug reports and pull requests are welcome on GitHub at
https://github.com/riboseinc/bc-drill-manager. This project is intended to be a
safe, welcoming space for collaboration, and contributors are expected to adhere
to the http://contributor-covenant.org[Contributor Covenant] code of conduct.

== License

The gem is available as open source under the terms of the
https://opensource.org/licenses/MIT[MIT License].

== Code of Conduct

Everyone interacting in the `bc-drill-manager` project’s codebases, issue
trackers, chat rooms and mailing lists is expected to follow the
https://github.com/riboseinc/bc-drill-manager/blob/master/CODE_OF_CONDUCT.adoc[code
of conduct].
